// Auto-generated by LibreLane
module neural_osc(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input rst_n,
  input sample_tick,
  input[9:0] pitch,
  input[7:0] morph,
  input w_we,
  input[5:0] w_addr,
  input[15:0] w_wdata,
  output[15:0] sample
);
endmodule
