// Auto-generated by LibreLane
module chaos_engine(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input rst_n,
  input sample_tick,
  input[1:0] map_sel,
  input[5:0] rate,
  input[7:0] r_seed,
  output[15:0] sample
);
endmodule
