// Auto-generated by LibreLane
module bytebeat(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input rst_n,
  input sample_tick,
  input[3:0] formula_sel,
  input[7:0] t_inc,
  output[15:0] sample
);
endmodule
