// Auto-generated by LibreLane
module sid_engine(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input rst_n,
  input sample_tick,
  input[15:0] v0_freq,
  input[15:0] v1_freq,
  input[15:0] v2_freq,
  input[2:0] v0_wave,
  input[2:0] v1_wave,
  input[2:0] v2_wave,
  input[7:0] v0_pw,
  input[7:0] v1_pw,
  input[7:0] v2_pw,
  input[2:0] ring_en,
  input[2:0] sync_en,
  output[15:0] sample
);
endmodule
