// Auto-generated by LibreLane
module ks_engine(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input clk,
  input rst_n,
  input sample_tick,
  input pluck,
  input[9:0] period,
  output[15:0] sample
);
endmodule
